name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
      
    - name: Check for Platforms installed
      uses: buluma/setup-cordova@v0.0.3
      with:
        # Apache Cordova command to execute
        exec: cordova platform ls && javac -version

  testout-put:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo ${{needs.test.outputs}} ${{needs.test.outputs.output2}}
      
  build:

    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Install Cordova & node-properties-parser
      run: sudo npm install -g cordova && sudo npm install node-properties-parser
      
    - name: Build Android
      # You may pin to the exact commit or the version.
      # uses: buluma/setup-cordova@1640182b19452591866992ddd5ac0c36c6b750ec
      uses: buluma/setup-cordova@v0.0.3
      with:
        # Apache Cordova command to execute
        exec: javac -version && cordova build android --verbose
#         exec: cordova platform ls
  
  buildout-put:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo ${{needs.build.outputs}} ${{needs.build.outputs.output2}}
