---
name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Publish `v1.2.3` tags as releases.
    tags:
      - v*


jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v2

    - name: remove java 11
      run: ls /usr/lib/jvm/ && sudo rm -r /usr/lib/jvm/adoptopenjdk-11-hotspot-amd64 && ls /usr/lib/jvm/

    - name: check and instl jdk-8
      run: sudo apt install openjdk-8-jdk openjdk-8-jre && java -version

    - name: Verify Java11 removed and java-8-openjdk-amd64 installed
      run: ls /usr/lib/jvm/

    - name: check for jdk path and export
      run: ls /usr/lib/jvm/ && export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 && export PATH=$JAVA_HOME/bin:$PATH

    - name: check java version
      run: java -version && echo $JAVA_HOME

    - name: check javac version
      run: javac -version && echo $JAVA_HOME

  # test-output:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     - run: echo ${{needs.test.outputs}} ${{needs.test.outputs.output2}}
      
  build:

    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v2
    - name: remove java 11
      run: ls /usr/lib/jvm/ && sudo rm -r /usr/lib/jvm/adoptopenjdk-11-hotspot-amd64

    - name: Instl jdk-8 & Check installed version
      run: sudo apt install openjdk-8-jdk openjdk-8-jre && java -version

    - name: Install Cordova & node-properties-parser
      run: sudo npm install -g cordova && sudo npm install node-properties-parser
      
    - name: Build Android
      uses: buluma/setup-cordova@v0.0.3
      with:
        # Apache Cordova command to execute with java verification
        exec: java -version && cordova build android --verbose

    - name: Upload APK File
      uses: actions/upload-artifact@v2
      with:
        # Define Package file for release workflow
        name: wvef-app-debug.apk
        path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
  
  pre-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download APK File from Build
      uses: actions/download-artifact@v2
      with:
        # Download Package file from build workflow
        name: wvef-app-debug.apk

    - name: Verify APK exists
      run: ls -a /home/runner/work/WVEF-Mobile-App/WVEF-Mobile-App

    - name: APK files release
      run: tar -cvf wvef-app-debug.apk /home/runner/work/WVEF-Mobile-App/WVEF-Mobile-App/app-debug.apk

    # - name: Upload Artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: wvef-app-debug-apk
    #     path: wvef-app-debug.apk

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: /home/runner/work/WVEF-Mobile-App/WVEF-Mobile-App/app-debug.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Create Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.2
        release_name: v1.0.2
        draft: false
        prerelease: false

    - name: Download APK File from Build
      uses: actions/download-artifact@v2
      with:
        # Download Package file from build workflow
        name: wvef-app-debug.apk

    - uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: /home/runner/work/WVEF-Mobile-App/WVEF-Mobile-App/app-debug.apk
        asset_name: wvef-app-debug.${{ steps.create_release.outputs.id }}.apk
        asset_content_type: application/apk

    - uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}
