name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v2
    # - name: Set up JDK 8
    #   uses: actions/setup-java@v2
    #   with:
    #     java-version: '8'
    #     distribution: 'adopt'

    - name: remove java 11
      run: ls /usr/lib/jvm/ && sudo rm -r /usr/lib/jvm/adoptopenjdk-11-hotspot-amd64 && java -version

    - name: check and instl jdk-8
      # run: sudo apt-get install openjdk-8-jdk
      run: sudo apt install openjdk-8-jdk openjdk-8-jre

    - name: check for jdk path and export
      # run: ls /usr/lib/jvm/
      run: ls /usr/lib/jvm/ && export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 && export PATH=$JAVA_HOME/bin:$PATH

    - name: check java version
      run: java -version && echo $JAVA_HOME

    - name: check javac version
      run: javac -version && echo $JAVA_HOME

  test-output:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo ${{needs.test.outputs}} ${{needs.test.outputs.output2}}
      
#   build:

#     runs-on: ubuntu-latest
#     needs: test

#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up JDK 8
#       uses: actions/setup-java@v2
#       with:
#         java-version: '8'
#         distribution: 'adopt'

#     - name: Install Cordova & node-properties-parser
#       run: sudo npm install -g cordova && sudo npm install node-properties-parser
      
#     - name: Build Android
#       # You may pin to the exact commit or the version.
#       # uses: buluma/setup-cordova@1640182b19452591866992ddd5ac0c36c6b750ec
#       uses: buluma/setup-cordova@v0.0.3
#       with:
#         # Apache Cordova command to execute
#         exec: java -version && cordova build android --verbose
# #         exec: cordova platform ls
  
#   build-output:
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - run: echo ${{needs.build.outputs}} ${{needs.build.outputs.output2}}
