---
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.tag }}
    steps:
      - id: step1
        run: echo "::set-output name=test::tag"
      - id: step2
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: remove java 11
      run: ls /usr/lib/jvm/ && sudo rm -r /usr/lib/jvm/adoptopenjdk-11-hotspot-amd64 && ls /usr/lib/jvm/

    - name: check and instl jdk-8
      run: sudo apt install openjdk-8-jdk openjdk-8-jre && java -version

    - name: Verify Java11 removed and java-8-openjdk-amd64 installed
      run: ls /usr/lib/jvm/

    - name: check for jdk path and export
      run: ls /usr/lib/jvm/ && export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 && export PATH=$JAVA_HOME/bin:$PATH

    - name: check java version
      run: java -version && echo $JAVA_HOME

    - name: check javac version
      run: javac -version && echo $JAVA_HOME



  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo ${{needs.test.outputs.output1}} ${{needs.test.outputs.output2}}

